version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo-container
    restart: always
    volumes:
      - mongo_data:/data/db
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.runCommand('ping')"]
      interval: 30s
      retries: 5
      start_period: 10s
      timeout: 10s

  nodejs-app:
    build: .
    container_name: nodejs-container
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - app_network

volumes:
  mongo_data:

networks:
  app_network:
